SUPABASE_URL = "https://fieksocintrggtlidnjj.supabase.co/rest/v1/"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZWtzb2NpbnRyZ2d0bGlkbmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4MzI5NTQsImV4cCI6MjEwNTQwODk1NH0.DYyBdtJLQy6-hMxAWxkH6G1r8noJV_KVN2SH79YNCpM"
